# Generated by Django 5.1.6 on 2025-03-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_order_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_hot_deal',
            field=models.BooleanField(default=False),
        ),
    ]
